name: Action Sample

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  deployment:
    runs-on: self-runner
    steps:
      - name: execute echo command
        run: echo "Hello World!"
