name: Action Sample

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: execute echo command
        run: |
          cd /var/www/html/wp3
          git pull
